In [1]:
import pandas as pd
import numpy as np
dict1={'Names':['Ramesh','Suresh','Sathish',np.nan],
       'Age':[np.nan,22,24,26],
       'City':['Hyd','Blr',np.nan,'Pune']}
d1=pd.DataFrame(dict1)
d1.to_csv('data1.csv',index=False)

In [37]:
import pandas as pd
import numpy as np
dict2={'Names':['Ramesh','Suresh','Sathish',None],
       'Age':[None,22,24,26],
       'City':['Hyd','Blr',None,'Pune']}
d2=pd.DataFrame(dict1)
d2.to_csv('data2.csv',index=False)

In [3]:
d1.isnull()

Names    Age   City
0  False   True  False
1  False  False  False
2  False  False   True
3   True  False  False

In [38]:
d1.isnull().sum()

Names    1
Age      1
City     1
dtype: int64

**Difference between NaN and None**

- For **object types** we will use None

- For **number types** we will use NaN

In [39]:
np.nan+5

nan

In [40]:
None+5

TypeError: unsupported operand type(s) for +: 'NoneType' and 'int'

In [9]:
arr1=np.array([1,2,3,np.nan])
arr2=np.array([1,2,3,None])
arr1

array([ 1.,  2.,  3., nan])

In [10]:
arr2

array([1, 2, 3, None], dtype=object)

In [11]:
arr1.dtype,arr2.dtype

(dtype('float64'), dtype('O'))

In [15]:
np.sum(arr1),np.nansum(arr1)

(np.float64(nan), np.float64(6.0))

In [12]:
np.sum(arr2)

TypeError: unsupported operand type(s) for +: 'int' and 'NoneType'

In [13]:
d2.dtypes

Names     object
Age      float64
City      object
dtype: object

**astype**

In [14]:
arr3=arr2.astype(float)
arr3

array([ 1.,  2.,  3., nan])

In [15]:
d2['Age'].values.astype(int)

C:\Users\P.Siddartha\AppData\Local\Temp\ipykernel_24156\3751503362.py:1: RuntimeWarning: invalid value encountered in cast
  d2['Age'].values.astype(int)


array([-9223372036854775808,                   22,                   24,
                         26])

**Fill with a Random value**

In [16]:
d1.fillna(30)
#Inplace=True to overide

Names   Age  City
0   Ramesh  30.0   Hyd
1   Suresh  22.0   Blr
2  Sathish  24.0    30
3       30  26.0  Pune

In [17]:
d1

Names   Age  City
0   Ramesh   NaN   Hyd
1   Suresh  22.0   Blr
2  Sathish  24.0   NaN
3      NaN  26.0  Pune

**Fill with a random value based on column**

In [18]:
#first select the column
d1['Age'].fillna(30)        # not recommended

0    30.0
1    22.0
2    24.0
3    26.0
Name: Age, dtype: float64

**By using methods**

- pad

- ffill

- bfill

- backfill

In [19]:
import warnings
warnings.filterwarnings('ignore')
d1.fillna(method='pad')

Names   Age  City
0   Ramesh   NaN   Hyd
1   Suresh  22.0   Blr
2  Sathish  24.0   Blr
3  Sathish  26.0  Pune

In [20]:
d1.fillna(method='pad',axis=1)  #horizontal

Names     Age  City
0   Ramesh  Ramesh   Hyd
1   Suresh    22.0   Blr
2  Sathish    24.0  24.0
3      NaN    26.0  Pune

In [21]:
d1.fillna(method='pad',axis=0)  #vertical

Names   Age  City
0   Ramesh   NaN   Hyd
1   Suresh  22.0   Blr
2  Sathish  24.0   Blr
3  Sathish  26.0  Pune

In [22]:
d1.fillna(method='ffill')

Names   Age  City
0   Ramesh   NaN   Hyd
1   Suresh  22.0   Blr
2  Sathish  24.0   Blr
3  Sathish  26.0  Pune

In [23]:
d1.fillna(method='ffill',axis=1)

Names     Age  City
0   Ramesh  Ramesh   Hyd
1   Suresh    22.0   Blr
2  Sathish    24.0  24.0
3      NaN    26.0  Pune

In [24]:
d1.fillna(method='bfill',axis=1)

Names   Age  City
0   Ramesh   Hyd   Hyd
1   Suresh  22.0   Blr
2  Sathish  24.0   NaN
3     26.0  26.0  Pune

In [25]:
d1.fillna(method='bfill',axis=0)

Names   Age  City
0   Ramesh  22.0   Hyd
1   Suresh  22.0   Blr
2  Sathish  24.0  Pune
3      NaN  26.0  Pune

In [26]:
d1.fillna(method='backfill',axis=0)

Names   Age  City
0   Ramesh  22.0   Hyd
1   Suresh  22.0   Blr
2  Sathish  24.0  Pune
3      NaN  26.0  Pune

In [27]:
d1.fillna(method='backfill',axis=1)

Names   Age  City
0   Ramesh   Hyd   Hyd
1   Suresh  22.0   Blr
2  Sathish  24.0   NaN
3     26.0  26.0  Pune

**Mean-Median-Median**

- when data has outliers go with **Median**

-  Otherwise fill with Mean

- For a categoricak data with Mode

In [37]:
age_mean=d1['Age'].mean()
d1['Age'].fillna(age_mean)

0    24.0
1    22.0
2    24.0
3    26.0
Name: Age, dtype: float64

In [38]:
d1['City'].mode()

0     Blr
1     Hyd
2    Pune
Name: City, dtype: object

In [39]:
d1

Names   Age  City
0   Ramesh   NaN   Hyd
1   Suresh  22.0   Blr
2  Sathish  24.0   NaN
3      NaN  26.0  Pune

In [40]:
new_row={'Names':'Satish','Age':24,'City':'Pune'}

In [42]:
len(d1)

4

In [44]:
d1.loc[len(d1)]=new_row
d1

Names   Age  City
0   Ramesh   NaN   Hyd
1   Suresh  22.0   Blr
2  Sathish  24.0   NaN
3      NaN  26.0  Pune
4   Satish  24.0  Pune

In [28]:
d1['City']
d1['City'].mode()
d1['City'].mode().values
city_mode=d1['City'].mode().values[0]
d1['City'].fillna(city_mode)

0     Hyd
1     Blr
2     Blr
3    Pune
Name: City, dtype: object

In [29]:
age_mean=d1['Age'].mean()
d1['Age'].fillna(age_mean)

0    24.0
1    22.0
2    24.0
3    26.0
Name: Age, dtype: float64

**KNN Immputer**

- K- Nearest Neighbours

- Where k = hyper parameters which means the user can change

- Idea: Instead of taking all the samples average

   - First fix the neighbours number i.e k
 
   - Then find the neighbours using distance metric
 
   - Then take the average of those samples to fill the missing value

In [49]:
import sklearn
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import LabelEncoder
from sklearn.impute import KNNImputer

In [50]:
import numpy as np
import pandas as pd
from sklearn.impute import KNNImputer
X=[[1,2,np.nan],[3,np.nan,3],[np.nan,60,5],[8,8,7]]
pd.DataFrame(X)

0     1    2
0  1.0   2.0  NaN
1  3.0   NaN  3.0
2  NaN  60.0  5.0
3  8.0   8.0  7.0

In [53]:
import numpy as np
from sklearn.impute import KNNImputer
X=[[1,2,np.nan],[3,np.nan,3],
   [np.nan,60,5],[8,8,7]]
imputer=KNNImputer(n_neighbors=2,weights='uniform')
imputer.fit_transform(X)

array([[ 1. ,  2. ,  5. ],
       [ 3. , 31. ,  3. ],
       [ 5.5, 60. ,  5. ],
       [ 8. ,  8. ,  7. ]])

In [ ]:
EDA steps

1.- read the data

2.- separate categorical and numerical columns

3.- Data,quick checks

     shape , columns, dtypes

4.- Null value analysis
 A) Check is any Null values are present
 B) Fill the null values with Median or KNNImputer for Numerical Columns
 C) Fill the null values with Mode for categorical columns

5.- Do some data preprocessing
   if any column is corrupted
   ex: Numerical values in categorical columns
   ex: categorical values in numerical columns

6.- Drop the ID types columns
  which means a data has more unique labels
  Drop single value column

7. Categorical column analysis
   A) Frequency table
   B) bar charts
   C) pie charts

8. Numerical Column analysis
   A) Histogram
   B) Distribution
   C) Box plot

9. Outlier analysis
   Impute the outliers with Median
   Impute the outliers by using winsorizatin

10. Find the Correlation between numerical columns
    Heat map

11. Convert cat to Numerical
    A) LabelEncoder
    B) One hot encoder

12. Scale the data
    A) Z standardization
    B) Normalization

by the time of 12 steps, we achieve 3 Things
i) Cleaned data
ii) Data in the form of complete Numerical 
iii) we have some understanding the data

13. we will try to select the important feature for ML 
    A) PCA: principle component analysis(will be covered in ML)

Finally we achieve 3 data sets

1. Till step-11
   with out scale but data in Numerical format
2. Till step-12
with scaling data in numerical format

3. Till step-13
   Pca data

